spring.application.name=demo
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=morillonoriegaf@gmail.com
spring.mail.password=uwck yfwb cqtj erhv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


groq.api.key=${GROQ_API_KEY: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}
groq.api.url=${GROQ_API_URL:https://api.groq.com/openai/v1/chat/completions}
groq.model=${GROQ_MODEL:llama-3.1-8b-instant}


spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.security.user.name=william   
spring.security.user.password=
logging.level.org.springframework.security=DEBUG
spring.thymeleaf.cache=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true


spring.data.mongodb.uri=mongodb://localhost:27017/extincor_db
